"""Deterministic synthetic conversation generator.

Produces the fixed test corpus (Appendix D.2):

  - 10 short   (10-20 turns, single topic)
  - 20 medium  (30-50 turns, 2-3 topic shifts)
  - 15 long    (80-100 turns, multiple shifts, cross-cutting dependencies)
  -  5 edge    (rapid topic switching, very long single turns, contradictions)

Conversations contain domain vocabulary and code blocks (for later router
tests) and long-range references to earlier decisions (for context-loss tests).
Output is written to ``tests/fixtures/generated/`` (gitignored).
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "generated"

# ---------------------------------------------------------------------------
# Domain content: per-topic feature + decisions (facts) that turn templates use.
# The topic table lives in the system (auditor.topics) so splinter/ never imports
# from the bench; it is re-exported here for backward compatibility.
# ---------------------------------------------------------------------------
from auditor.topics import TOPICS  # noqa: E402

CODE_SNIPPETS = [
    "def handle_{feat}():\n    return {{\"ok\": True}}\n",
    "async def process_{feat}(request):\n    await request.accept()\n    return request\n",
    "class {Feat}Service:\n    def __init__(self):\n        self._cache = {{}}\n",
]

# ---------------------------------------------------------------------------
# Prose domain (P4 code-vs-prose comparison, 2026-08-23).
# Deliberately separate from TOPICS: prose conversations are generated by
# ``generate_prose()`` into their own output dir with their own RNG stream, so
# the seed-2026 code fixture (the measured test set) is untouched. No code
# blocks, no engineering vocabulary — the fact terms are prose-flavored so the
# deterministic diagnostic's term extraction sees a genuinely different
# distribution (the P4 claim: code and prose decay optimally at different
# multipliers).
# ---------------------------------------------------------------------------
PROSE_TOPICS = {
    "docs_style": {
        "feature": "documentation style guide",
        "aspects": ["tone", "sentence length", "headings", "glossary", "voice"],
        "decisions": {
            "tone": "direct and conversational",
            "sentence length": "under twenty words on average",
            "headings": "question-form headings",
            "glossary": "every acronym defined at first use",
            "voice": "active voice, second person",
        },
    },
    "editorial": {
        "feature": "engineering blog",
        "aspects": ["review process", "publishing cadence", "attribution", "draft review", "metrics"],
        "decisions": {
            "review process": "two peer reviews before publish",
            "publishing cadence": "one post per fortnight",
            "attribution": "credit by pull-request author",
            "draft review": "drafts open in shared folder",
            "metrics": "read time and return visits tracked",
        },
    },
    "onboarding": {
        "feature": "new-hire guide",
        "aspects": ["first week", "mentor pairing", "permissions", "checklists", "feedback cadence"],
        "decisions": {
            "first week": "read-only access until day five",
            "mentor pairing": "paired with a senior reviewer",
            "permissions": "granted in weekly batches",
            "checklists": "each role has a printed checklist",
            "feedback cadence": "feedback every friday",
        },
    },
    "release_notes": {
        "feature": "release notes",
        "aspects": ["changelog format", "deprecation notices", "breaking changes", "version naming", "user quotes"],
        "decisions": {
            "changelog format": "grouped by topic not date",
            "deprecation notices": "announced two releases early",
            "breaking changes": "bolded in summary section",
            "version naming": "calendar-based names",
            "user quotes": "quotes only with written consent",
        },
    },
}

# ---------------------------------------------------------------------------
# Long-horizon domain (P4's testable decay corpus, 2026-08-23).
#
# P4 needs conversations where the *relevant* fact is OLD at query time — only
# then does the decay multiplier govern whether it survives into the assembled
# context (the flat 91.1%/78.1% curves came from corpora where relevant facts
# are always recent). Each horizon conversation has:
#
#   - an ESTABLISH phase: n_topics topic blocks, every aspect decided exactly
#     once (deterministic order, single copy of each fact — precise age
#     control),
#   - a RECAP phase: R queries in the SAME order, each re-asking one established
#     fact at age == establish length E (the recap reply is stored only AFTER
#     its own assembly is judged, and each recap targets a distinct aspect, so
#     no recap chunk can leak the next query's facts).
#
# Domain structure encodes the white paper's P4 premise:
#   - code:    references cluster in time  -> E in {10, 20}: age_factor 1.0/2.0,
#              NO stale penalty, so code facts survive aggressive decay — the
#              knee lands at the high multipliers,
#   - prose:   longer-range dependencies   -> E in {24, 32}: stale penalty
#              (age > 20 halves the score), so prose facts die at the low
#              multipliers.
# Measurement lessons that shaped this corpus (2026-08-23):
#   - The adaptive budget's high-relevance feedback (bigger store -> bigger
#     budget -> looser cutoff) washes out the decay signal, so the P4 sweep
#     holds the budget FIXED at 1000 tokens (the ultra-small tier's floor) —
#     the same confound-isolation the deterministic P2 diagnostic applies.
#   - Facts must sit in the no-stale regime to be multiplier-sensitive: the
#     stale factor (x0.5 at age > 20) makes facts older than 20 turns
#     unretrievable at ANY multiplier (a decay-formula finding, reported in
#     the white paper P4 section).
#   - Fact terms must be absent from every OTHER aspect's chunks (aspect names,
#     feature names, query templates) or unrelated chunks false-hit them
#     (verified by test_horizon_decision_terms_are_distinctive).
#
# Decision values are chosen so their extracted fact-terms are non-empty,
# non-stopword, and pairwise DISJOINT across every aspect of both domains —
# otherwise one fact's terms could "hit" through an unrelated chunk and flatten
# the measurement (verified by test_horizon_decision_terms_are_distinctive).
# Own RNG streams (4041 code / 5051 prose), own output dirs, disjoint from the
# seed-2026 code fixture and the seed-3031 prose corpus.
# ---------------------------------------------------------------------------
HORIZON_TOPICS = {
    "auth_service": {
        "feature": "auth service",
        "aspects": ["token lifetime", "refresh strategy", "session backend", "scope policy",
                    "password hashing", "client authentication", "logout handling", "account lockout",
                    "oauth flows", "password resets"],
        "decisions": {
            "token lifetime": "fifteen-minute expiring tokens",
            "refresh strategy": "rolling refresh rotation",
            "session backend": "postgres session store",
            "scope policy": "read and write scopes",
            "password hashing": "argon2 password hashing",
            "client authentication": "client certificate authentication",
            "logout handling": "immediate access revocation",
            "account lockout": "graduated lockout timers",
            "oauth flows": "explicit oauth consent screens",
            "password resets": "tokenized reset links",
        },
    },
    "inventory_schema": {
        "feature": "inventory schema",
        "aspects": ["partitioning", "indexing", "soft delete", "migrations", "constraints",
                    "backup strategy", "data retention", "schema versioning",
                    "sync scheduling", "compaction"],
        "decisions": {
            "partitioning": "sharded by warehouse id",
            "indexing": "hot-path composite indexes",
            "soft delete": "archived flag column",
            "migrations": "squashed monthly migrations",
            "constraints": "cascade purge constraints",
            "backup strategy": "nightly snapshot backups",
            "data retention": "two-year archive spans",
            "schema versioning": "numbered schema releases",
            "sync scheduling": "overnight sync cycles",
            "compaction": "periodic compaction sweeps",
        },
    },
    "audit_pipeline": {
        "feature": "audit pipeline",
        "aspects": ["transport", "enrichment", "batching", "retention", "alerts",
                    "event ordering", "sampling policy", "consumer lag",
                    "schema drift detection", "replay capability"],
        "decisions": {
            "transport": "kafka audit transport",
            "enrichment": "service metadata enrichment",
            "batching": "thousand-message batches",
            "retention": "ninety-day hot retention",
            "alerts": "anomaly alerting rules",
            "event ordering": "sequence number ordering",
            "sampling policy": "stratified trace sampling",
            "consumer lag": "lag threshold alarms",
            "schema drift detection": "immutable schema locks",
            "replay capability": "replay from cold archives",
        },
    },
    "release_flow": {
        "feature": "release flow",
        "aspects": ["branching", "staging", "rollback", "signing", "freeze windows",
                    "feature flags", "hotfix policy", "release candidates",
                    "environment parity", "shipping gates"],
        "decisions": {
            "branching": "trunk branching model",
            "staging": "ephemeral staging environments",
            "rollback": "instant rollback snapshots",
            "signing": "signed release artifacts",
            "freeze windows": "holiday release freezes",
            "feature flags": "permanent feature flags",
            "hotfix policy": "emergency hotfix lanes",
            "release candidates": "tagged release candidates",
            "environment parity": "mirrored environment parity",
            "shipping gates": "approval shipping gates",
        },
    },
    "api_gateway": {
        "feature": "api gateway",
        "aspects": ["throttling", "routing", "caching", "observability", "token checks",
                    "request logging", "rate limiting", "tls policy",
                    "timeouts", "payload transforms"],
        "decisions": {
            "throttling": "bucket throttling quotas",
            "routing": "circuit breaker routing",
            "caching": "edge response caching",
            "observability": "tracing header propagation",
            "token checks": "gateway jwt verification",
            "request logging": "structured request logs",
            "rate limiting": "per-key rate ceilings",
            "tls policy": "mandatory tls enforcement",
            "timeouts": "staggered timeout caps",
            "payload transforms": "payload transform filters",
        },
    },
}

PROSE_HORIZON_TOPICS = {
    "team_communication": {
        "feature": "team communication",
        "aspects": ["meeting cadence", "status updates", "decision log", "feedback", "knowledge sharing", "oncall", "documentation", "conflict resolution"],
        "decisions": {
            "meeting cadence": "daily standup huddles",
            "status updates": "written async status posts",
            "decision log": "shared choice ledger",
            "feedback": "semiannual feedback circles",
            "knowledge sharing": "rotating demo showcases",
            "oncall": "staggered oncall rotations",
            "documentation": "living handbook pages",
            "conflict resolution": "facilitated mediation sessions",
        },
    },
    "product_planning": {
        "feature": "product planning",
        "aspects": ["roadmap", "prioritization", "discovery", "success metrics", "experiments", "stakeholder updates", "launch reviews", "postmortems"],
        "decisions": {
            "roadmap": "two-quarter horizon roadmaps",
            "prioritization": "impact scoring boards",
            "discovery": "customer discovery sprints",
            "success metrics": "adoption and stickiness metrics",
            "experiments": "bounded experiment windows",
            "stakeholder updates": "fortnightly stakeholder briefings",
            "launch reviews": "prelaunch readiness reviews",
            "postmortems": "blameless incident writeups",
        },
    },
    "hiring": {
        "feature": "hiring",
        "aspects": ["interview format", "candidate experience", "scorecards", "referrals", "onboarding", "diversity", "offers", "retention pulse"],
        "decisions": {
            "interview format": "structured panel interviews",
            "candidate experience": "same-week review letters",
            "scorecards": "calibrated rubric scorecards",
            "referrals": "double-sided referral bonuses",
            "onboarding": "mentored first-month plans",
            "diversity": "slate diversity targets",
            "offers": "team-vetted offer packages",
            "retention pulse": "annual retention checkins",
        },
    },
    "content_strategy": {
        "feature": "content strategy",
        "aspects": ["calendar", "voice", "distribution", "analytics", "keyword research", "community", "partnerships", "licensing"],
        "decisions": {
            "calendar": "seasonal content calendars",
            "voice": "plainspoken brand voice",
            "distribution": "newsletter and social distribution",
            "analytics": "readership cohort analytics",
            "keyword research": "keyword research cycles",
            "community": "moderated community forums",
            "partnerships": "cross-promotion partnership deals",
            "licensing": "syndicated reprint licensing",
        },
    },
    "workspace_culture": {
        "feature": "workspace culture",
        "aspects": ["hours", "hybrid rhythm", "rituals", "wellness", "recognition", "learning", "planning", "transparency"],
        "decisions": {
            "hours": "core collaboration hours",
            "hybrid rhythm": "three-day hybrid rhythm",
            "rituals": "weekly gratitude rituals",
            "wellness": "monthly wellness stipends",
            "recognition": "peer nomination awards",
            "learning": "lunchtime skill workshops",
            "planning": "quarterly offsite retreats",
            "transparency": "open decision digests",
        },
    },
}

HORIZON_ESTABLISH_USER = "Let's settle {aspect} for the {feature}."
HORIZON_ESTABLISH_ASST = (
    "For the {feature}, {aspect} should use {decision}."
    " Key decision: {aspect} = {decision}."
)
HORIZON_ESTABLISH_PROSE_FILLER = (
    " That arrangement is settled for now. We can revisit it later if the situation changes."
)
# Per-topic code-domain content (2026-08-23): the P4 sweep holds the budget at
# the 1000-token floor, so the code store must bind it — bigger chunks mean
# fewer slots, which is what lets the decay multiplier push old facts out. The
# snippet + sentence are topic-specific (shared filler would push inter-reply
# cosine past the dedup threshold and merge the fact chunks away).
CODE_TOPIC_SNIPPETS = {
    "auth_service": "def verify_auth(request):\n    return check_signature(request.headers)\n",
    "inventory_schema": "def list_inventory(page):\n    return query_page(page, limit=100)\n",
    "audit_pipeline": "def emit_audit(event):\n    serializer.write(event)\n",
    "release_flow": "def promote_build(artifact):\n    signer.sign(artifact)\n",
    "api_gateway": "def route_request(path):\n    return lookup_route(path)\n",
}
CODE_TOPIC_FILLERS = {
    "auth_service": " We keep the material in the vault notebook afterwards.",
    "inventory_schema": " The inventory crew reviews the numbers every evening.",
    "audit_pipeline": " The operations crew checks the counters each morning.",
    "release_flow": " The delivery crew signs the packages every cycle.",
    "api_gateway": " The network crew monitors the traffic each hour.",
}
HORIZON_RECAP_ASST = (
    "The {aspect} for the {feature} is {decision}."
    " Key decision: {aspect} = {decision}."
)
# Varied recap wording, cycled deterministically: identical recap queries would
# score ~0.9 against each other and swamp the decay signal (near-identical
# chunks fill the top budget slots at every multiplier, flattening the curve).
HORIZON_RECAP_USER_TPL = [
    "Remind me what we decided for {aspect} in the {feature}.",
    "What was the final decision on {aspect} for the {feature}?",
    "Can you restate the {aspect} decision for the {feature}?",
    "I need the {aspect} decision for the {feature} again.",
    "What did we agree for {aspect} in the {feature}?",
    "Restate the {aspect} policy for the {feature}.",
]

HORIZON_ESTABLISH_LENGTHS = {
    "code": [1, 2],            # E in {10, 20}  (no stale; age_factor 1.0/2.0)
    "prose": [3, 4],           # E in {24, 32}  (stale penalty; age_factor 2.4/3.0)
}
HORIZON_PER_ESTABLISH = {"code": 10, "prose": 8}
HORIZON_RECAP_TURNS = 20
HORIZON_CONVS_PER_LENGTH = 3


def _horizon_turns(rng: random.Random, domain: str, topics: list[str]) -> tuple[list[dict], int]:
    """Establish-then-recap turns for a long-horizon conversation.

    Returns (turns, establish_length). Every aspect is decided exactly once in
    an establishment pass, then the first ``R`` aspects are re-asked in a recap
    phase at age E. The establish pass grows the store past the fixed 1000-token
    sweep budget so the decay multiplier genuinely governs selection.
    """
    topics_data = HORIZON_TOPICS if domain == "code" else PROSE_HORIZON_TOPICS
    per_topic = HORIZON_PER_ESTABLISH[domain]
    turns: list[dict] = []
    established: list[tuple[str, str]] = []  # (aspect, decision)
    for topic in topics:
        data = topics_data[topic]
        for aspect in data["aspects"][:per_topic]:
            decision = data["decisions"][aspect]
            user = HORIZON_ESTABLISH_USER.format(
                feature=data["feature"], aspect=aspect,
            )
            if domain == "code":
                code = rng.choice(CODE_SNIPPETS).format(
                    feat=data["feature"].replace(" ", "_"),
                    Feat="".join(w.capitalize() for w in data["feature"].split()),
                )
                topic_snippet = CODE_TOPIC_SNIPPETS[topic]
                asst = (HORIZON_ESTABLISH_ASST.format(
                    feature=data["feature"], aspect=aspect, decision=decision,
                ) + "\n```python\n" + code + "```\n```python\n"
                     + topic_snippet + "```" + CODE_TOPIC_FILLERS[topic])
            else:
                asst = (HORIZON_ESTABLISH_ASST.format(
                    feature=data["feature"], aspect=aspect, decision=decision,
                ) + HORIZON_ESTABLISH_PROSE_FILLER)
            turns.append({"role": "user", "content": user})
            turns.append({"role": "assistant", "content": asst})
            established.append((aspect, decision))
    establish_len = len(established)
    recap_n = min(HORIZON_RECAP_TURNS, establish_len)
    for idx, (aspect, decision) in enumerate(established[:recap_n]):
        data = topics_data[topics[0]]
        user = HORIZON_RECAP_USER_TPL[idx % len(HORIZON_RECAP_USER_TPL)].format(
            feature=data["feature"], aspect=aspect,
        )
        asst = HORIZON_RECAP_ASST.format(
            feature=data["feature"], aspect=aspect, decision=decision,
        )
        turns.append({"role": "user", "content": user})
        turns.append({"role": "assistant", "content": asst})
    return turns, establish_len


def generate_horizon(output_dir: str | Path, seed: int, domain: str,
                     n_convs_per_length: int = HORIZON_CONVS_PER_LENGTH) -> list[dict]:
    """Generate the P4 long-horizon corpus for one domain.

    ``domain`` is "code" (HORIZON_TOPICS, engineering features with code
    blocks) or "prose" (PROSE_HORIZON_TOPICS, prose-flavored). Each
    establishment length gets ``n_convs_per_length`` conversations, so the
    sweep sees a graded age distribution. Own RNG stream per call.
    """
    if domain not in ("code", "prose"):
        raise ValueError(f"unknown horizon domain: {domain!r}")
    topics_data = HORIZON_TOPICS if domain == "code" else PROSE_HORIZON_TOPICS
    rng = random.Random(seed)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    topic_names = list(topics_data)
    written: list[dict] = []
    idx = 0
    for n_topics in HORIZON_ESTABLISH_LENGTHS[domain]:
        for _ in range(n_convs_per_length):
            idx += 1
            topics = rng.sample(topic_names, n_topics)
            turns, establish_len = _horizon_turns(rng, domain, topics)
            prefix = "horizon" if domain == "code" else "prose_horizon"
            conv = {
                "conversation_id": f"{prefix}_{idx:03d}",
                "profile": "longhorizon",
                "domain": domain,
                "topic": topics[0],
                "establish_turns": establish_len,
                "recap_turns": min(HORIZON_RECAP_TURNS, establish_len),
                "turns": turns,
            }
            path = out / f"{prefix}_{idx:03d}.json"
            path.write_text(json.dumps(conv, indent=2), encoding="utf-8")
            written.append(conv)
    return written


# ---------------------------------------------------------------------------
# P9 densest-duplicate corpus (2026-08-23).
#
# P9 ("keeping the information-densest duplicate beats keeping the most
# recent") needs conversations with ENGINEERED duplicate pairs whose cosine
# exceeds the dedup threshold (0.92): each aspect is stated once in a DENSE
# form (the canonical reply, ~33 tokens) and once in a VERBOSE form (the same
# fact + a repeated Key-decision line + filler, ~85 tokens — the repeated
# decision tokens keep the pair cosine ~0.93, above the 0.92 merge threshold).
# The dedup then merges the pair and keeps one version — the only policy
# difference is WHICH one survives:
#
#   - order "recency_favors_verbose": dense first, verbose restatement later
#     (a recency-keeping policy would keep the verbose copy),
#   - order "control": verbose first, dense restatement later (both policies
#     keep the dense copy — the control for the A/B).
#
# Recap queries at a fixed age then measure sufficiency-per-1k-tokens (fact
# presence weighted by the kept copy's token cost). Own RNG stream (6061),
# own output dir, reuses PROSE_HORIZON_TOPICS (term-clean decisions verified
# by test_horizon_decision_terms_are_distinctive) and the horizon recap
# templates. The filler sentences are leak-checked against all fact terms.
# ---------------------------------------------------------------------------
P9_DENSE_ASST = HORIZON_ESTABLISH_ASST  # "For the {feature}, {aspect} should use {decision}. Key decision: {aspect} = {decision}."
# Verbose restatement: the dense text + one repeated Key-decision line + two
# short filler clauses (all term-leak-free). The repeated decision line keeps
# the dense<->verbose cosine above the 0.92 dedup threshold for ALL 40 aspects
# (measured with the default drone: min 0.933, p50 0.963) while inflating the
# token count ~1.7x (33 -> ~57). Full filler sentences were measured to dilute
# the pair below the threshold — only decision-line repetition + short clauses
# survive it.
P9_VERBOSE_ASST = (
    "For the {feature}, {aspect} should use {decision}. Key decision: {aspect} = {decision}."
    " Key decision: {aspect} = {decision}."
    " We noted this in the notes. This stays for now."
)
# The verbose turn needs its OWN query: the fixture answer map keeps the FIRST
# answer for a repeated query, so an identical "Let's settle..." would store
# the dense reply twice and the verbose copy would never enter the store.
P9_VERBOSE_USER = "Confirm again that {aspect} is still the right call for the {feature}."
P9_ASPECTS_PER_CONV = 6
P9_CONVS_PER_ORDER = 2
P9_SEED = 6061


def _p9_verbose_asst(aspect: str, decision: str, feature: str) -> str:
    return P9_VERBOSE_ASST.format(feature=feature, aspect=aspect, decision=decision)


def generate_p9(output_dir: str | Path, seed: int = P9_SEED,
                n_convs_per_order: int = P9_CONVS_PER_ORDER) -> list[dict]:
    """Generate the P9 engineered-duplicate corpus.

    Two conversations per order (recency_favors_verbose / control); each
    states P9_ASPECTS_PER_CONV aspects twice (dense + verbose) then re-asks
    them in a recap phase. Returns the conversation dicts.
    """
    rng = random.Random(seed)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    topics = list(PROSE_HORIZON_TOPICS)
    written: list[dict] = []
    idx = 0
    for order in ("recency_favors_verbose", "control"):
        for _ in range(n_convs_per_order):
            idx += 1
            topic = rng.choice(topics)
            data = PROSE_HORIZON_TOPICS[topic]
            aspects = rng.sample(list(data["decisions"]), P9_ASPECTS_PER_CONV)
            pairs = [(a, data["decisions"][a]) for a in aspects]
            turns: list[dict] = []
            for i, (aspect, decision) in enumerate(pairs):
                dense = P9_DENSE_ASST.format(
                    feature=data["feature"], aspect=aspect, decision=decision)
                verbose = _p9_verbose_asst(aspect, decision, data["feature"])
                user = HORIZON_ESTABLISH_USER.format(
                    feature=data["feature"], aspect=aspect)
                verbose_user = P9_VERBOSE_USER.format(
                    feature=data["feature"], aspect=aspect)
                first, second = (dense, verbose) if order == "recency_favors_verbose" else (verbose, dense)
                first_user, second_user = (
                    (user, verbose_user) if order == "recency_favors_verbose" else (verbose_user, user))
                turns.append({"role": "user", "content": first_user})
                turns.append({"role": "assistant", "content": first})
                turns.append({"role": "user", "content": second_user})
                turns.append({"role": "assistant", "content": second})
            for i, (aspect, decision) in enumerate(pairs):
                user = HORIZON_RECAP_USER_TPL[i % len(HORIZON_RECAP_USER_TPL)].format(
                    feature=data["feature"], aspect=aspect)
                asst = HORIZON_RECAP_ASST.format(
                    feature=data["feature"], aspect=aspect, decision=decision)
                turns.append({"role": "user", "content": user})
                turns.append({"role": "assistant", "content": asst})
            conv = {
                "conversation_id": f"p9_{idx:03d}",
                "profile": "p9",
                "domain": "prose",
                "topic": topic,
                "order": order,
                "aspects_per_conv": P9_ASPECTS_PER_CONV,
                "aspects": aspects,
                "turns": turns,
            }
            path = out / f"p9_{idx:03d}.json"
            path.write_text(json.dumps(conv, indent=2), encoding="utf-8")
            written.append(conv)
    return written


PROSE_USER_TPL = [
    "Let's improve the {feature}. How should we handle {aspect}?",
    "What does our team prefer for {aspect} in the {feature}?",
    "Can we reconsider how {aspect} works in the {feature}?",
    "We need to settle {aspect} for the {feature}. Walk me through the options.",
    "How does {aspect} fit with {ref}?",
    "Draft the guidance for {aspect} in the {feature}.",
]

PROSE_ASST_TPL = [
    "For the {feature}, {aspect} should use {decision}. Key decision: {aspect} = {decision}.",
    "The right approach for {aspect} is {decision}. Recall that earlier we decided {ref}.",
    "We'll set {aspect} to {decision} for the {feature}. This keeps {ref} consistent.",
    "Recommendation: {aspect} follows {decision} in the {feature}. Established choice: {ref}.",
]


def _turns_for_prose_topic(rng: random.Random, topic: str, count: int,
                           established_facts: list[str]) -> list[dict]:
    """Like ``_turns_for_topic`` but for the prose domain: no code blocks,
    prose-flavored facts, prose templates."""
    data = PROSE_TOPICS[topic]
    turns: list[dict] = []
    facts = [f"{k}={v}" for k, v in data["decisions"].items()]
    for i in range(count):
        aspect = rng.choice(data["aspects"])
        decision = data["decisions"][aspect]
        ref = rng.choice(established_facts) if established_facts and rng.random() < 0.5 else aspect
        user = rng.choice(PROSE_USER_TPL).format(
            feature=data["feature"], aspect=aspect, ref=ref
        )
        asst = rng.choice(PROSE_ASST_TPL).format(
            feature=data["feature"], aspect=aspect, decision=decision, ref=ref,
        )
        turns.append({"role": "user", "content": user})
        turns.append({"role": "assistant", "content": asst})
    established_facts.append(f"{data['feature']}: {facts[0]}")
    return turns


def generate_prose(output_dir: str | Path, seed: int = 3031,
                   n_long: int = 12) -> list[dict]:
    """Generate prose-domain long conversations (P4's prose corpus).

    Disjoint from the code fixture: own RNG stream (default seed 3031), own
    output dir, own topic set. Writes ``prose_NNN.json`` files with profile
    "prose". Long-profile shape (4 topics, ~20-25 turns per topic) mirrors the
    code longs so the decay replay compares like-for-like.
    """
    rng = random.Random(seed)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    topic_names = list(PROSE_TOPICS)
    written: list[dict] = []
    for i in range(n_long):
        established_facts: list[str] = []
        topics = rng.sample(topic_names, min(4, len(topic_names)))
        turns: list[dict] = []
        for t in topics:
            per = rng.randint(20, 25)
            turns.extend(_turns_for_prose_topic(rng, t, per // 2, established_facts))
        conv = {
            "conversation_id": f"prose_{i + 1:03d}",
            "profile": "prose",
            "topic": topics[0],
            "turns": turns,
        }
        path = out / f"prose_{i + 1:03d}.json"
        path.write_text(json.dumps(conv, indent=2), encoding="utf-8")
        written.append(conv)
    return written

USER_TPL = [
    "Let's work on the {feature}. How should we handle {aspect}?",
    "What would you recommend for {aspect} in our {feature}?",
    "Can we change how {aspect} works in the {feature}?",
    "We need to address {aspect} for the {feature}. Walk me through it.",
    "How does {aspect} fit with {ref}?",
    "Show me the code for {aspect} in the {feature}.",
]

ASST_TPL = [
    "For the {feature}, {aspect} should use {decision}. Key decision: {aspect} = {decision}.\n```python\n{code}\n```",
    "The right approach for {aspect} is {decision}. Recall that earlier we decided {ref}.\n```python\n{code}\n```",
    "We'll set {aspect} to {decision} for the {feature}. This keeps {ref} consistent.\n```python\n{code}\n```",
]


def _fact_list(topic: str) -> list[str]:
    return [f"{k}={v}" for k, v in TOPICS[topic]["decisions"].items()]


def _turns_for_topic(rng: random.Random, topic: str, count: int,
                     established_facts: list[str]) -> list[dict]:
    data = TOPICS[topic]
    turns: list[dict] = []
    facts = _fact_list(topic)
    for i in range(count):
        aspect = rng.choice(data["aspects"])
        decision = data["decisions"][aspect]
        ref = rng.choice(established_facts) if established_facts and rng.random() < 0.5 else aspect
        code = rng.choice(CODE_SNIPPETS).format(
            feat=data["feature"].replace(" ", "_"),
            Feat="".join(w.capitalize() for w in data["feature"].split()),
        )
        user = rng.choice(USER_TPL).format(
            feature=data["feature"], aspect=aspect, ref=ref
        )
        asst = rng.choice(ASST_TPL).format(
            feature=data["feature"], aspect=aspect, decision=decision,
            ref=ref, code=code,
        )
        turns.append({"role": "user", "content": user})
        turns.append({"role": "assistant", "content": asst})
    # Record this topic's facts as established for cross-references.
    established_facts.append(f"{data['feature']}: {facts[0]}")
    return turns


def _make_conversation(rng: random.Random, profile: str, idx: int,
                       topic_names: list[str]) -> dict:
    conv_id = f"{profile}_{idx:03d}"
    established_facts: list[str] = []
    turns: list[dict] = []

    if profile == "short":
        topic = rng.choice(topic_names)
        n = rng.randint(10, 20)
        turns.extend(_turns_for_topic(rng, topic, n // 2, established_facts))

    elif profile == "medium":
        n_topics = rng.randint(2, 3)
        topics = rng.sample(topic_names, min(n_topics, len(topic_names)))
        per = rng.randint(15, 25)
        for t in topics:
            turns.extend(_turns_for_topic(rng, t, per // 2, established_facts))

    elif profile == "long":
        topics = rng.sample(topic_names, min(4, len(topic_names)))
        per = rng.randint(20, 25)
        for t in topics:
            turns.extend(_turns_for_topic(rng, t, per // 2, established_facts))

    elif profile == "edge":
        edge_type = idx % 3
        if edge_type == 0:
            # Rapid topic switching: many short blocks.
            for t in rng.sample(topic_names, len(topic_names)):
                turns.extend(_turns_for_topic(rng, t, 3, established_facts))
        elif edge_type == 1:
            # Very long single turns.
            topic = rng.choice(topic_names)
            data = TOPICS[topic]
            long_user = (
                "Given the long history of this project, consolidate everything "
                f"about the {data['feature']}. " + " ".join(
                    f"({k}) {v};" for k, v in data["decisions"].items()
                )
            )
            turns.append({"role": "user", "content": long_user})
            turns.append({"role": "assistant",
                          "content": f"Summary of {data['feature']}: " + ", ".join(_fact_list(topic))})
        else:
            # Contradictory instructions: same aspect, opposite decisions.
            topic = rng.choice(topic_names)
            data = TOPICS[topic]
            aspect = data["aspects"][0]
            turns.append({"role": "user",
                          "content": f"Set {aspect} to the default for the {data['feature']}."})
            turns.append({"role": "assistant",
                          "content": f"OK, {aspect} defaulted for the {data['feature']}."})
            turns.append({"role": "user",
                          "content": f"Actually, never mind — override {aspect} to a non-standard value now."})
            turns.append({"role": "assistant",
                          "content": f"Understood, overriding {aspect} for the {data['feature']}."})

    return {
        "conversation_id": conv_id,
        "profile": profile,
        "topic": topic_names[0],
        "turns": turns,
    }


# ---------------------------------------------------------------------------
# P11 return corpus (2026-08-24).
#
# The comb probe measured that only 45% of the existing fixture's return turns
# are lexically retrievable — composition queries ("How does rollbacks fit
# with order schema: normalization=3NF?") never lexically name the old facts —
# and that lexical-overlap retrieval reaches 76-87% recall on the retrievable
# ones. This corpus builds SHADOW-style *pure-fact* return questions that
# lexically name the old decision:
#
#   phase A: establish facts for topic X (aspect -> decision, one turn each)
#   phase B: >= 21 turns of a different topic (clears the stale wall; the
#            store fills with other-topic chunks and A's facts age past it)
#   phase C: topic X returns — pure-fact questions ("What did we settle for
#            {aspect} on the {feature}?") whose answers restate the A facts,
#            one multi-key question (two aspects at once), and one abstain
#            question (an aspect never established — the fact is genuinely
#            absent and must not be fabricated).
#
# Own RNG stream (seed 7071), own output dir (generated_return), reuses
# PROSE_HORIZON_TOPICS (term-clean decisions locked by
# test_horizon_decision_terms_are_distinctive). Leak invariants are
# regression-locked in test_return_corpus.py: A-decision terms appear only in
# A-phase answers and C-phase answers; return queries share a topic word with
# their fact chunks (the probe's retrievability condition).
# ---------------------------------------------------------------------------
RETURN_SEED = 7071
RETURN_ESTABLISH_ASPECTS = 4
RETURN_FILLER_TURNS = 22  # > the stale wall (20), so A facts age past it
RETURN_CONVS = 6

RETURN_QUERY_TPL = "What did we settle for {aspect} on the {feature}?"
RETURN_MULTI_QUERY_TPL = (
    "Which decisions did we settle for {aspect1} and {aspect2} on the {feature}?"
)
RETURN_MULTI_ASST = (
    "For the {feature}, {aspect1} should use {decision1}."
    " For the {feature}, {aspect2} should use {decision2}."
    " Key decisions: {aspect1} = {decision1}; {aspect2} = {decision2}."
)
RETURN_ABSTAIN_ASST = "There is no information regarding {aspect} for the {feature}."


def _return_turns(rng: random.Random, establish_topic: str,
                  filler_topic: str) -> tuple[list[dict], dict]:
    """Build one return conversation: establish -> filler -> return."""
    data = PROSE_HORIZON_TOPICS[establish_topic]
    filler = PROSE_HORIZON_TOPICS[filler_topic]
    turns: list[dict] = []
    established: list[tuple[str, str]] = []
    aspects = rng.sample(
        list(data["decisions"]),
        min(RETURN_ESTABLISH_ASPECTS, len(data["decisions"])),
    )
    for aspect in aspects:  # phase A: establish facts
        decision = data["decisions"][aspect]
        turns.append({"role": "user",
                      "content": HORIZON_ESTABLISH_USER.format(
                          feature=data["feature"], aspect=aspect)})
        turns.append({"role": "assistant",
                      "content": HORIZON_ESTABLISH_ASST.format(
                          feature=data["feature"], aspect=aspect, decision=decision)})
        established.append((aspect, decision))
    filler_aspects = list(filler["decisions"])
    for _ in range(RETURN_FILLER_TURNS):  # phase B: filler, clears the stale wall
        aspect = rng.choice(filler_aspects)
        decision = filler["decisions"][aspect]
        turns.append({"role": "user",
                      "content": HORIZON_ESTABLISH_USER.format(
                          feature=filler["feature"], aspect=aspect)})
        turns.append({"role": "assistant",
                      "content": HORIZON_ESTABLISH_ASST.format(
                          feature=filler["feature"], aspect=aspect, decision=decision)})
    return_queries: list[str] = []
    for aspect, decision in established:  # phase C: topic returns, pure-fact
        q = RETURN_QUERY_TPL.format(feature=data["feature"], aspect=aspect)
        a = HORIZON_ESTABLISH_ASST.format(
            feature=data["feature"], aspect=aspect, decision=decision)
        turns.append({"role": "user", "content": q})
        turns.append({"role": "assistant", "content": a})
        return_queries.append(q)
    if len(established) >= 2:  # multi-key: two facts at once
        (a1, d1), (a2, d2) = established[:2]
        q = RETURN_MULTI_QUERY_TPL.format(
            feature=data["feature"], aspect1=a1, aspect2=a2)
        a = RETURN_MULTI_ASST.format(
            feature=data["feature"], aspect1=a1, decision1=d1,
            aspect2=a2, decision2=d2)
        turns.append({"role": "user", "content": q})
        turns.append({"role": "assistant", "content": a})
        return_queries.append(q)
    absent = next(a for a in data["decisions"]
                  if a not in {e[0] for e in established})
    q = RETURN_QUERY_TPL.format(feature=data["feature"], aspect=absent)
    a = RETURN_ABSTAIN_ASST.format(feature=data["feature"], aspect=absent)
    turns.append({"role": "user", "content": q})
    turns.append({"role": "assistant", "content": a})
    return turns, {
        "establish_topic": establish_topic,
        "filler_topic": filler_topic,
        "establish_turns": len(established),
        "filler_turns": RETURN_FILLER_TURNS,
        "return_queries": return_queries,
        "abstain_query": q,
    }


def generate_return(output_dir: str | Path, seed: int = RETURN_SEED,
                    n_convs: int = RETURN_CONVS) -> list[dict]:
    """Generate the P11 return corpus (pure-fact topic-return structure)."""
    rng = random.Random(seed)
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    topic_names = list(PROSE_HORIZON_TOPICS)
    written: list[dict] = []
    for i in range(n_convs):
        est_topic, fill_topic = rng.sample(topic_names, 2)
        turns, meta = _return_turns(rng, est_topic, fill_topic)
        conv = {
            "conversation_id": f"return_{i + 1:03d}",
            "profile": "return",
            "domain": "prose",
            **meta,
            "turns": turns,
        }
        path = out / f"return_{i + 1:03d}.json"
        path.write_text(json.dumps(conv, indent=2), encoding="utf-8")
        written.append(conv)
    return written


def generate(output_dir: str | Path = OUTPUT_DIR, seed: int = 2026) -> list[dict]:
    rng = random.Random(seed)
    topic_names = list(TOPICS)
    profiles = (
        [("short", 10)] + [("medium", 20)] + [("long", 15)] + [("edge", 5)]
    )
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[dict] = []
    idx = 0
    for profile, count in profiles:
        for i in range(count):
            conv = _make_conversation(rng, profile, i + 1, topic_names)
            path = out / f"{profile}_{i + 1:03d}.json"
            path.write_text(json.dumps(conv, indent=2), encoding="utf-8")
            written.append(conv)
            idx += 1
    return written


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=str(OUTPUT_DIR))
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--prose", action="store_true",
                        help="generate the prose-domain corpus (P4) instead")
    parser.add_argument("--prose-output", default=str(Path(OUTPUT_DIR).parent / "generated_prose"))
    parser.add_argument("--horizon", action="store_true",
                        help="generate the P4 long-horizon corpora "
                             "(tests/fixtures/generated_horizon + generated_prose_horizon)")
    parser.add_argument("--p9", action="store_true",
                        help="generate the P9 engineered-duplicate corpus "
                             "(tests/fixtures/generated_p9)")
    parser.add_argument("--return-corpus", dest="return_corpus", action="store_true",
                        help="generate the P11 return corpus "
                             "(tests/fixtures/generated_return)")
    args = parser.parse_args()
    if args.return_corpus:
        out_dir = Path(OUTPUT_DIR).parent / "generated_return"
        convs = generate_return(out_dir, seed=RETURN_SEED)
        total_turns = sum(len(c["turns"]) for c in convs)
        print(f"Generated {len(convs)} P11 return conversations -> {out_dir}")
        print(f"Total turns: {total_turns}")
        return 0
    if args.p9:
        out_dir = Path(OUTPUT_DIR).parent / "generated_p9"
        convs = generate_p9(out_dir, seed=P9_SEED)
        total_turns = sum(len(c["turns"]) for c in convs)
        print(f"Generated {len(convs)} P9 conversations -> {out_dir}")
        print(f"Total turns: {total_turns}")
        return 0
    if args.horizon:
        code_dir = Path(OUTPUT_DIR).parent / "generated_horizon"
        prose_dir = Path(OUTPUT_DIR).parent / "generated_prose_horizon"
        code_convs = generate_horizon(code_dir, seed=4041, domain="code")
        prose_convs = generate_horizon(prose_dir, seed=5051, domain="prose")
        for domain, convs in (("code", code_convs), ("prose", prose_convs)):
            total_turns = sum(len(c["turns"]) for c in convs)
            establish = sorted({c["establish_turns"] for c in convs})
            print(f"Generated {len(convs)} {domain} long-horizon conversations"
                  f" (establish lengths {establish})")
            print(f"Total turns: {total_turns}")
        return 0
    if args.prose:
        convs = generate_prose(args.prose_output, seed=args.seed)
        total_turns = sum(len(c["turns"]) for c in convs)
        print(f"Generated {len(convs)} prose conversations -> {args.prose_output}")
        print(f"Total turns: {total_turns}")
        return 0
    convs = generate(args.output, args.seed)
    total_turns = sum(len(c["turns"]) for c in convs)
    print(f"Generated {len(convs)} conversations -> {args.output}")
    print(f"Total turns: {total_turns}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())